version: '3.8'

services:
  db:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    tmpfs:
      - /var/lib/mysql
    security_opt:
      - seccomp:unconfined